### ISSUE TITLE
GBoard not working

### ISSUE THREAD

**Issue by chickendrop89** [chickendrop89/magisk-nik-gapps#2]
Upon clicking on a text field
```
3417  3417 E FeaturePermissionsManager: FeaturePermissionsManager.isFeaturePermissionsGranted():701 Feature [2132018708] is not registered
3417  3417 E FeaturePermissionsManager: 	at iqv.o(PG:2)
3417  3417 E FeaturePermissionsManager: 	at btv.q(PG:68)
3417  3417 E FeaturePermissionsManager: 	at dfg.onStartInputView(PG:30)
3417  3417 E FeaturePermissionsManager: 	at android.inputmethodservice.InputMethodService.doStartInput(InputMethodService.java:3370)
3417  3417 E FeaturePermissionsManager: 	at android.inputmethodservice.InputMethodService$InputMethodImpl.startInput(InputMethodService.java:862)
3417  3417 E FeaturePermissionsManager: 	at android.inputmethodservice.InputMethodService$InputMethodImpl.dispatchStartInput(InputMethodService.java:891)
3417  3417 E FeaturePermissionsManager: 	at android.inputmethodservice.IInputMethodWrapper.executeMessage(IInputMethodWrapper.java:201)
3417  3417 E FeaturePermissionsManager: 	at com.android.internal.os.HandlerCaller$MyHandler.handleMessage(HandlerCaller.java:44)
3417  3417 E FeaturePermissionsManager: 	at android.os.Handler.dispatchMessage(Handler.java:107)
3417  3417 E FeaturePermissionsManager: 	at android.os.Looper.loopOnce(Looper.java:232)
3417  3417 E FeaturePermissionsManager: 	at android.os.Looper.loop(Looper.java:317)
3417  3417 E FeaturePermissionsManager: 	at android.app.ActivityThread.main(ActivityThread.java:8592)
3417  3417 E FeaturePermissionsManager: 	at java.lang.reflect.Method.invoke(Native Method)
3417  3417 E FeaturePermissionsManager: 	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:580)
3417  3417 E FeaturePermissionsManager: 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:878)
```

----------------------------

Upon opening "Preferences" in GBoard menu
```
11434 11434 E AndroidRuntime: FATAL EXCEPTION: main
11434 11434 E AndroidRuntime: Process: com.google.android.inputmethod.latin, PID: 11434
11434 11434 E AndroidRuntime: java.lang.IllegalStateException: Failed to get identifier from name: setting_languages
11434 11434 E AndroidRuntime: 	at jkr.b(PG:7)
11434 11434 E AndroidRuntime: 	at jkr.a(PG:2)
11434 11434 E AndroidRuntime: 	at jkr.c(PG:1)
11434 11434 E AndroidRuntime: 	at com.google.android.libraries.inputmethod.preferencewidgets.CommonPreferenceFragment.hC(PG:4)
11434 11434 E AndroidRuntime: 	at com.google.android.libraries.inputmethod.preferencewidgets.CommonPreferenceFragment.bd(PG:3)
11434 11434 E AndroidRuntime: 	at com.google.android.libraries.inputmethod.preferencewidgets.CommonPreferenceFragment.au(PG:1)
11434 11434 E AndroidRuntime: 	at aiy.e(PG:8)
11434 11434 E AndroidRuntime: 	at com.google.android.libraries.inputmethod.preferencewidgets.CommonPreferenceFragment.e(PG:1)
11434 11434 E AndroidRuntime: 	at com.google.android.apps.inputmethod.libs.languageselection.preference.LanguageSettingFragment.e(PG:1)
11434 11434 E AndroidRuntime: 	at aw.d(PG:176)
11434 11434 E AndroidRuntime: 	at ar.al(PG:112)
11434 11434 E AndroidRuntime: 	at ar.am(PG:10)
11434 11434 E AndroidRuntime: 	at ar.ab(PG:8)
11434 11434 E AndroidRuntime: 	at aj.run(PG:111)
11434 11434 E AndroidRuntime: 	at android.os.Handler.handleCallback(Handler.java:959)
11434 11434 E AndroidRuntime: 	at android.os.Handler.dispatchMessage(Handler.java:100)
11434 11434 E AndroidRuntime: 	at android.os.Looper.loopOnce(Looper.java:232)
11434 11434 E AndroidRuntime: 	at android.os.Looper.loop(Looper.java:317)
11434 11434 E AndroidRuntime: 	at android.app.ActivityThread.main(ActivityThread.java:8592)
11434 11434 E AndroidRuntime: 	at java.lang.reflect.Method.invoke(Native Method)
11434 11434 E AndroidRuntime: 	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:580)
11434 11434 E AndroidRuntime: 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:878)
```

**Comment by chkndrp** [comment]
To note, official NikGApps packages require a clean environment (/data not populated yet) for installing GBoard.

https://github.com/nikgapps/project/blob/2faed8a4c40fbe415821c8c453bce73797015034/NikGapps/build/PackageConstants.py#L6
